/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List components */
        get: operations["list_components_v1_components_get"];
        put?: never;
        /** Create a component */
        post: operations["create_component_v1_components_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/components/{component_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a component by id */
        get: operations["get_component_v1_components__component_id__get"];
        /** Replace a component */
        put: operations["update_component_v1_components__component_id__put"];
        post?: never;
        /** Delete a component */
        delete: operations["delete_component_v1_components__component_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Category
         * @enum {string}
         */
        Category: "base" | "vegetable" | "sauce" | "topping";
        /** ComponentCreate */
        ComponentCreate: {
            /** Allergens */
            allergens?: string[];
            /**
             * Blacklisted
             * @default false
             */
            blacklisted: boolean;
            category: components["schemas"]["Category"];
            /** Cooking Methods */
            cooking_methods: components["schemas"]["CookingMethodSpecSchema"][];
            default_cooking_method: components["schemas"]["CookingMethod"];
            default_portion: components["schemas"]["PortionSchema"];
            /** Dietary Tags */
            dietary_tags?: string[];
            /** Flavor Tags */
            flavor_tags?: string[];
            /** Image Url */
            image_url?: string | null;
            macros_per_100g: components["schemas"]["MacrosSchema"];
            /** Name */
            name: string;
            /** Shelf Life Days */
            shelf_life_days?: number | null;
        };
        /** ComponentList */
        ComponentList: {
            /** Items */
            items: components["schemas"]["ComponentRead"][];
            /** Total */
            total: number;
        };
        /** ComponentRead */
        ComponentRead: {
            /** Allergens */
            allergens?: string[];
            /**
             * Blacklisted
             * @default false
             */
            blacklisted: boolean;
            category: components["schemas"]["Category"];
            /** Cooking Methods */
            cooking_methods: components["schemas"]["CookingMethodSpecSchema"][];
            default_cooking_method: components["schemas"]["CookingMethod"];
            default_portion: components["schemas"]["PortionSchema"];
            /** Dietary Tags */
            dietary_tags?: string[];
            /** Flavor Tags */
            flavor_tags?: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Url */
            image_url?: string | null;
            macros_per_100g: components["schemas"]["MacrosSchema"];
            /** Name */
            name: string;
            /** Shelf Life Days */
            shelf_life_days?: number | null;
        };
        /**
         * CookingMethod
         * @enum {string}
         */
        CookingMethod: "boil" | "steam" | "blanch" | "pan_fry" | "roast" | "air_fry" | "grill" | "bake" | "toast" | "raw" | "no_prep" | "blend_cold" | "blend_hot" | "heat" | "whisk_cold" | "whisk_hot" | "reduce" | "saute_simmer" | "crumble" | "custom";
        /** CookingMethodSpecSchema */
        CookingMethodSpecSchema: {
            /** Approx Minutes */
            approx_minutes?: number | null;
            /**
             * Can Cook With Others
             * @default true
             */
            can_cook_with_others: boolean;
            method: components["schemas"]["CookingMethod"];
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MacrosSchema */
        MacrosSchema: {
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Fiber G */
            fiber_g: number;
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number;
        };
        /** PortionSchema */
        PortionSchema: {
            unit: components["schemas"]["PortionUnit"];
            /** Value */
            value: number;
        };
        /**
         * PortionUnit
         * @enum {string}
         */
        PortionUnit: "g" | "ml" | "pc";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_components_v1_components_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["Category"] | null;
                include_blacklisted?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_component_v1_components_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_component_v1_components__component_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_component_v1_components__component_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_component_v1_components__component_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
