/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List components */
        get: operations["list_components_v1_components_get"];
        put?: never;
        /** Create a component */
        post: operations["create_component_v1_components_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/components/{component_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a component by id */
        get: operations["get_component_v1_components__component_id__get"];
        /** Replace a component */
        put: operations["update_component_v1_components__component_id__put"];
        post?: never;
        /** Delete a component */
        delete: operations["delete_component_v1_components__component_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List history events */
        get: operations["list_events_v1_history_get"];
        put?: never;
        /** Append a history event */
        post: operations["create_event_v1_history_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a history event */
        delete: operations["delete_event_v1_history__event_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile */
        get: operations["get_profile_v1_me_profile_get"];
        /** Update user profile */
        put: operations["update_profile_v1_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pantry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pantry items */
        get: operations["list_items_v1_pantry_get"];
        put?: never;
        /** Add a pantry item */
        post: operations["create_item_v1_pantry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pantry/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a pantry item */
        put: operations["update_item_v1_pantry__item_id__put"];
        post?: never;
        /** Delete a pantry item */
        delete: operations["delete_item_v1_pantry__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/planned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List planned meals (optionally by range) */
        get: operations["list_planned_v1_planned_get"];
        put?: never;
        /** Schedule a meal */
        post: operations["create_planned_v1_planned_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/planned/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a planned meal */
        delete: operations["delete_planned_v1_planned__meal_id__delete"];
        options?: never;
        head?: never;
        /** Update a planned meal (move/restatus) */
        patch: operations["update_planned_v1_planned__meal_id__patch"];
        trace?: never;
    };
    "/v1/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ratings (optionally per bowl) */
        get: operations["list_ratings_v1_ratings_get"];
        put?: never;
        /** Add a rating */
        post: operations["create_rating_v1_ratings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a recipe from chosen components */
        post: operations["build_recipe_endpoint_v1_recipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Roll a bowl */
        post: operations["roll_bowl_v1_roll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roll/slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-roll a single slot */
        post: operations["reroll_one_slot_v1_roll_slot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved meals */
        get: operations["list_saved_v1_saved_get"];
        put?: never;
        /** Save a bowl snapshot */
        post: operations["create_saved_v1_saved_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a saved meal */
        delete: operations["delete_saved_v1_saved__meal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a shopping list from a bowl + portion count */
        post: operations["build_list_v1_shopping_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stores */
        get: operations["list_stores_v1_stores_get"];
        put?: never;
        /** Create a store */
        post: operations["create_store_v1_stores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stores/{store_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a store */
        put: operations["update_store_v1_stores__store_id__put"];
        post?: never;
        /** Delete a store and its prices */
        delete: operations["delete_store_v1_stores__store_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stores/{store_id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List prices for a store */
        get: operations["list_prices_v1_stores__store_id__prices_get"];
        /** Upsert a price (one per (store, component)) */
        put: operations["upsert_price_v1_stores__store_id__prices_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stores/{store_id}/prices/{price_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a price */
        delete: operations["delete_price_v1_stores__store_id__prices__price_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BuildRecipeRequestSchema
         * @description Build a Recipe from a list of chosen component ids.
         *
         *     The server reloads the components by id (cheap — pool is small) so
         *     the client doesn't have to round-trip the entire bowl payload.
         */
        BuildRecipeRequestSchema: {
            /** Component Ids */
            component_ids: string[];
            /** Forced Methods */
            forced_methods?: {
                [key: string]: components["schemas"]["CookingMethod"];
            };
        };
        /** BuildShoppingListRequest */
        BuildShoppingListRequest: {
            /** Component Ids */
            component_ids: string[];
            /** Portions */
            portions: number;
            /** Store Id */
            store_id?: string | null;
            /**
             * Use Pantry
             * @default true
             */
            use_pantry: boolean;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "base" | "vegetable" | "sauce" | "topping";
        /** ComponentCreate */
        ComponentCreate: {
            /** Allergens */
            allergens?: string[];
            /**
             * Blacklisted
             * @default false
             */
            blacklisted: boolean;
            category: components["schemas"]["Category"];
            /** Cooking Methods */
            cooking_methods: components["schemas"]["CookingMethodSpecSchema"][];
            default_cooking_method: components["schemas"]["CookingMethod"];
            default_portion: components["schemas"]["PortionSchema"];
            /** Dietary Tags */
            dietary_tags?: string[];
            /** Flavor Tags */
            flavor_tags?: string[];
            /** Image Url */
            image_url?: string | null;
            macros_per_100g: components["schemas"]["MacrosSchema"];
            /** Name */
            name: string;
            /** Shelf Life Days */
            shelf_life_days?: number | null;
        };
        /** ComponentList */
        ComponentList: {
            /** Items */
            items: components["schemas"]["ComponentRead"][];
            /** Total */
            total: number;
        };
        /** ComponentRead */
        ComponentRead: {
            /** Allergens */
            allergens?: string[];
            /**
             * Blacklisted
             * @default false
             */
            blacklisted: boolean;
            category: components["schemas"]["Category"];
            /** Cooking Methods */
            cooking_methods: components["schemas"]["CookingMethodSpecSchema"][];
            default_cooking_method: components["schemas"]["CookingMethod"];
            default_portion: components["schemas"]["PortionSchema"];
            /** Dietary Tags */
            dietary_tags?: string[];
            /** Flavor Tags */
            flavor_tags?: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Url */
            image_url?: string | null;
            macros_per_100g: components["schemas"]["MacrosSchema"];
            /** Name */
            name: string;
            /** Shelf Life Days */
            shelf_life_days?: number | null;
        };
        /**
         * CookingMethod
         * @enum {string}
         */
        CookingMethod: "boil" | "steam" | "blanch" | "pan_fry" | "roast" | "air_fry" | "grill" | "bake" | "toast" | "raw" | "no_prep" | "blend_cold" | "blend_hot" | "heat" | "whisk_cold" | "whisk_hot" | "reduce" | "saute_simmer" | "crumble" | "custom";
        /** CookingMethodSpecSchema */
        CookingMethodSpecSchema: {
            /** Approx Minutes */
            approx_minutes?: number | null;
            /**
             * Can Cook With Others
             * @default true
             */
            can_cook_with_others: boolean;
            method: components["schemas"]["CookingMethod"];
            /** Notes */
            notes?: string | null;
        };
        /** DirectionSchema */
        DirectionSchema: {
            axes?: components["schemas"]["FlavorAxesSchema"];
            /** Cuisines */
            cuisines?: string[];
            /** Moods */
            moods?: string[];
        };
        /** FeatureWeightsSchema */
        FeatureWeightsSchema: {
            /**
             * Direction Match
             * @default 0.25
             */
            direction_match: number;
            /**
             * Novelty
             * @default 0.2
             */
            novelty: number;
            /**
             * Nutrition Fit
             * @default 0.15
             */
            nutrition_fit: number;
            /**
             * Pantry Bonus
             * @default 0.05
             */
            pantry_bonus: number;
            /**
             * Price Fit
             * @default 0.2
             */
            price_fit: number;
            /**
             * Taste Match
             * @default 0.3
             */
            taste_match: number;
            /**
             * Time Fit
             * @default 0.1
             */
            time_fit: number;
        };
        /** FlavorAxesSchema */
        FlavorAxesSchema: {
            /**
             * Bold To Mild
             * @default 0
             */
            bold_to_mild: number;
            /**
             * Heavy To Light
             * @default 0
             */
            heavy_to_light: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HistoryEventCreate */
        HistoryEventCreate: {
            /** Bowl Id */
            bowl_id?: string | null;
            kind: components["schemas"]["HistoryEventKind"];
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * HistoryEventKind
         * @enum {string}
         */
        HistoryEventKind: "rolled" | "cooked" | "saved" | "rated" | "discarded";
        /** HistoryEventRead */
        HistoryEventRead: {
            /** Bowl Id */
            bowl_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["HistoryEventKind"];
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** HistoryList */
        HistoryList: {
            /** Items */
            items: components["schemas"]["HistoryEventRead"][];
            /** Total */
            total: number;
        };
        /** MacrosSchema */
        MacrosSchema: {
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Fiber G */
            fiber_g: number;
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number;
        };
        /**
         * MealSlot
         * @enum {string}
         */
        MealSlot: "breakfast" | "lunch" | "dinner" | "snack";
        /** PantryItemCreate */
        PantryItemCreate: {
            /**
             * Component Id
             * Format: uuid
             */
            component_id: string;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Opened
             * @default false
             */
            opened: boolean;
            /** Quantity */
            quantity: number;
            unit: components["schemas"]["PortionUnit"];
        };
        /** PantryItemRead */
        PantryItemRead: {
            /**
             * Component Id
             * Format: uuid
             */
            component_id: string;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Opened
             * @default false
             */
            opened: boolean;
            /** Quantity */
            quantity: number;
            unit: components["schemas"]["PortionUnit"];
        };
        /** PantryList */
        PantryList: {
            /** Items */
            items: components["schemas"]["PantryItemRead"][];
            /** Total */
            total: number;
        };
        /** PlannedMealCreate */
        PlannedMealCreate: {
            /** Bowl Snapshot */
            bowl_snapshot?: {
                [key: string]: unknown;
            };
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Planned For
             * Format: date
             */
            planned_for: string;
            slot: components["schemas"]["MealSlot"];
            /** @default planned */
            status: components["schemas"]["PlannedStatus"];
        };
        /** PlannedMealList */
        PlannedMealList: {
            /** Items */
            items: components["schemas"]["PlannedMealRead"][];
            /** Total */
            total: number;
        };
        /** PlannedMealRead */
        PlannedMealRead: {
            /** Bowl Snapshot */
            bowl_snapshot: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string;
            /**
             * Planned For
             * Format: date
             */
            planned_for: string;
            slot: components["schemas"]["MealSlot"];
            status: components["schemas"]["PlannedStatus"];
            /** Updated At */
            updated_at?: string | null;
        };
        /** PlannedMealUpdate */
        PlannedMealUpdate: {
            /** Notes */
            notes?: string | null;
            /** Planned For */
            planned_for?: string | null;
            slot?: components["schemas"]["MealSlot"] | null;
            status?: components["schemas"]["PlannedStatus"] | null;
        };
        /**
         * PlannedStatus
         * @enum {string}
         */
        PlannedStatus: "planned" | "shopped" | "cooked" | "skipped";
        /** PortionSchema */
        PortionSchema: {
            unit: components["schemas"]["PortionUnit"];
            /** Value */
            value: number;
        };
        /**
         * PortionUnit
         * @enum {string}
         */
        PortionUnit: "g" | "ml" | "pc";
        /** PriceList */
        PriceList: {
            /** Items */
            items: components["schemas"]["PriceRead"][];
            /** Total */
            total: number;
        };
        /** PriceRead */
        PriceRead: {
            /**
             * Component Id
             * Format: uuid
             */
            component_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Pack Price */
            pack_price: number;
            /** Pack Size */
            pack_size: number;
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** PriceUpsert */
        PriceUpsert: {
            /**
             * Component Id
             * Format: uuid
             */
            component_id: string;
            /** Pack Price */
            pack_price: number;
            /** Pack Size */
            pack_size: number;
        };
        /** RatingCreate */
        RatingCreate: {
            /**
             * Bowl Id
             * Format: uuid
             */
            bowl_id: string;
            /** Comment */
            comment?: string | null;
            /** Component Id */
            component_id?: string | null;
            /** Score */
            score: number;
        };
        /** RatingList */
        RatingList: {
            /** Items */
            items: components["schemas"]["RatingRead"][];
            /** Total */
            total: number;
        };
        /** RatingRead */
        RatingRead: {
            /**
             * Bowl Id
             * Format: uuid
             */
            bowl_id: string;
            /** Comment */
            comment?: string | null;
            /** Component Id */
            component_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Score */
            score: number;
        };
        /** RecipeBlockSchema */
        RecipeBlockSchema: {
            /** Can Cook With Others */
            can_cook_with_others: boolean;
            category: components["schemas"]["Category"];
            /** Components */
            components: components["schemas"]["ComponentRead"][];
            method: components["schemas"]["CookingMethod"];
            /** Steps */
            steps: components["schemas"]["RecipeStepSchema"][];
            /** Title */
            title: string;
            /** Total Minutes */
            total_minutes: number;
        };
        /** RecipeSchema */
        RecipeSchema: {
            /** Blocks */
            blocks: components["schemas"]["RecipeBlockSchema"][];
            /** Total Minutes */
            total_minutes: number;
        };
        /** RecipeStepSchema */
        RecipeStepSchema: {
            /** Duration Min */
            duration_min?: number | null;
            /**
             * Offset Min
             * @default 0
             */
            offset_min: number;
            /** Text */
            text: string;
        };
        /**
         * RerollSlotRequestSchema
         * @description Re-roll a single slot. The client keeps the rest of the bowl
         *     locally and splices in the returned slot. Server stays stateless.
         */
        RerollSlotRequestSchema: {
            /** Exclude Component Ids */
            exclude_component_ids?: string[];
            request: components["schemas"]["RollRequestSchema"];
            slot_category: components["schemas"]["Category"];
        };
        /** RollRequestSchema */
        RollRequestSchema: {
            /** Allergens Excluded */
            allergens_excluded?: string[];
            /** Blacklisted Ids */
            blacklisted_ids?: string[];
            /** Dietary Mode */
            dietary_mode?: string | null;
            direction?: components["schemas"]["DirectionSchema"];
            /** Forced Methods */
            forced_methods?: {
                [key: string]: components["schemas"]["CookingMethod"];
            };
            /** Recent Component Ids */
            recent_component_ids?: string[];
            /** Seed */
            seed?: number | null;
            /** Slots */
            slots: components["schemas"]["SlotSpecSchema"][];
            /** Tag Boosts */
            tag_boosts?: {
                [key: string]: number;
            };
            /**
             * Temperature
             * @default 0.5
             */
            temperature: number;
            /** Time Budget Min */
            time_budget_min?: number | null;
            weights?: components["schemas"]["FeatureWeightsSchema"];
        };
        /** RolledBowlSchema */
        RolledBowlSchema: {
            /** Slots */
            slots: components["schemas"]["RolledSlotSchema"][];
        };
        /** RolledSlotSchema */
        RolledSlotSchema: {
            component: components["schemas"]["ComponentRead"];
            /** Reasons */
            reasons: string[];
            /** Score */
            score: number;
        };
        /** SavedMealCreate */
        SavedMealCreate: {
            /** Bowl Snapshot */
            bowl_snapshot?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** SavedMealList */
        SavedMealList: {
            /** Items */
            items: components["schemas"]["SavedMealRead"][];
            /** Total */
            total: number;
        };
        /** SavedMealRead */
        SavedMealRead: {
            /** Bowl Snapshot */
            bowl_snapshot: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes: string;
        };
        /** ShoppingListItemRead */
        ShoppingListItemRead: {
            component: components["schemas"]["ComponentRead"];
            /** Line Price */
            line_price?: number | null;
            /** Pack Price */
            pack_price?: number | null;
            /** Pack Size */
            pack_size?: number | null;
            /** Packs To Buy */
            packs_to_buy?: number | null;
            /** Quantity Available In Pantry */
            quantity_available_in_pantry: number;
            /** Quantity Needed */
            quantity_needed: number;
            /** Quantity To Buy */
            quantity_to_buy: number;
        };
        /** ShoppingListRead */
        ShoppingListRead: {
            /** Has Missing Prices */
            has_missing_prices: boolean;
            /** Items */
            items: components["schemas"]["ShoppingListItemRead"][];
            /** Portions */
            portions: number;
            /** Total Price */
            total_price: number;
        };
        /** SlotSpecSchema */
        SlotSpecSchema: {
            category: components["schemas"]["Category"];
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /** StoreCreate */
        StoreCreate: {
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
        };
        /** StoreList */
        StoreList: {
            /** Items */
            items: components["schemas"]["StoreRead"][];
            /** Total */
            total: number;
        };
        /** StoreRead */
        StoreRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
        };
        /** UserProfileRead */
        UserProfileRead: {
            /** Allergens */
            allergens: string[];
            /** Default Time Budget Min */
            default_time_budget_min: number | null;
            /**
             * Dietary Mode
             * @enum {string}
             */
            dietary_mode: "" | "vegan" | "vegetarian" | "pescatarian";
            /** Goal */
            goal: string;
            /** Locale */
            locale: string;
            /** Onboarded */
            onboarded: boolean;
        };
        /** UserProfileUpdate */
        UserProfileUpdate: {
            /** Allergens */
            allergens?: string[];
            /** Default Time Budget Min */
            default_time_budget_min?: number | null;
            /**
             * Dietary Mode
             * @default
             * @enum {string}
             */
            dietary_mode: "" | "vegan" | "vegetarian" | "pescatarian";
            /**
             * Goal
             * @default
             */
            goal: string;
            /**
             * Locale
             * @default en
             */
            locale: string;
            /**
             * Onboarded
             * @default false
             */
            onboarded: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_components_v1_components_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["Category"] | null;
                include_blacklisted?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_component_v1_components_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_component_v1_components__component_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_component_v1_components__component_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_component_v1_components__component_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_history_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["HistoryEventKind"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_v1_history_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_v1_history__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_v1_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileRead"];
                };
            };
        };
    };
    update_profile_v1_me_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_v1_pantry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryList"];
                };
            };
        };
    };
    create_item_v1_pantry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PantryItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_v1_pantry__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PantryItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_v1_pantry__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_planned_v1_planned_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedMealList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_planned_v1_planned_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedMealCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedMealRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_planned_v1_planned__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_planned_v1_planned__meal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedMealUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedMealRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ratings_v1_ratings_get: {
        parameters: {
            query?: {
                bowl_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rating_v1_ratings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_recipe_endpoint_v1_recipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildRecipeRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roll_bowl_v1_roll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolledBowlSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reroll_one_slot_v1_roll_slot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerollSlotRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolledSlotSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_v1_saved_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMealList"];
                };
            };
        };
    };
    create_saved_v1_saved_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedMealCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMealRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_v1_saved__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_list_v1_shopping_list_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildShoppingListRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stores_v1_stores_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreList"];
                };
            };
        };
    };
    create_store_v1_stores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_store_v1_stores__store_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_store_v1_stores__store_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prices_v1_stores__store_id__prices_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_price_v1_stores__store_id__prices_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_price_v1_stores__store_id__prices__price_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
                price_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
