/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List components */
        get: operations["list_components_v1_components_get"];
        put?: never;
        /** Create a component */
        post: operations["create_component_v1_components_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/components/{component_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a component by id */
        get: operations["get_component_v1_components__component_id__get"];
        /** Replace a component */
        put: operations["update_component_v1_components__component_id__put"];
        post?: never;
        /** Delete a component */
        delete: operations["delete_component_v1_components__component_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Roll a bowl */
        post: operations["roll_bowl_v1_roll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roll/slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-roll a single slot */
        post: operations["reroll_one_slot_v1_roll_slot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a recipe from chosen components */
        post: operations["build_recipe_endpoint_v1_recipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BuildRecipeRequestSchema
         * @description Build a Recipe from a list of chosen component ids.
         *
         *     The server reloads the components by id (cheap — pool is small) so
         *     the client doesn't have to round-trip the entire bowl payload.
         */
        BuildRecipeRequestSchema: {
            /** Component Ids */
            component_ids: string[];
            /** Forced Methods */
            forced_methods?: {
                [key: string]: components["schemas"]["CookingMethod"];
            };
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "base" | "vegetable" | "sauce" | "topping";
        /** ComponentCreate */
        ComponentCreate: {
            category: components["schemas"]["Category"];
            /** Name */
            name: string;
            /** Image Url */
            image_url?: string | null;
            macros_per_100g: components["schemas"]["MacrosSchema"];
            default_portion: components["schemas"]["PortionSchema"];
            default_cooking_method: components["schemas"]["CookingMethod"];
            /** Cooking Methods */
            cooking_methods: components["schemas"]["CookingMethodSpecSchema"][];
            /** Flavor Tags */
            flavor_tags?: string[];
            /** Dietary Tags */
            dietary_tags?: string[];
            /** Allergens */
            allergens?: string[];
            /** Shelf Life Days */
            shelf_life_days?: number | null;
            /**
             * Blacklisted
             * @default false
             */
            blacklisted: boolean;
        };
        /** ComponentList */
        ComponentList: {
            /** Items */
            items: components["schemas"]["ComponentRead"][];
            /** Total */
            total: number;
        };
        /** ComponentRead */
        ComponentRead: {
            category: components["schemas"]["Category"];
            /** Name */
            name: string;
            /** Image Url */
            image_url?: string | null;
            macros_per_100g: components["schemas"]["MacrosSchema"];
            default_portion: components["schemas"]["PortionSchema"];
            default_cooking_method: components["schemas"]["CookingMethod"];
            /** Cooking Methods */
            cooking_methods: components["schemas"]["CookingMethodSpecSchema"][];
            /** Flavor Tags */
            flavor_tags?: string[];
            /** Dietary Tags */
            dietary_tags?: string[];
            /** Allergens */
            allergens?: string[];
            /** Shelf Life Days */
            shelf_life_days?: number | null;
            /**
             * Blacklisted
             * @default false
             */
            blacklisted: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * CookingMethod
         * @enum {string}
         */
        CookingMethod: "boil" | "steam" | "blanch" | "pan_fry" | "roast" | "air_fry" | "grill" | "bake" | "toast" | "raw" | "no_prep" | "blend_cold" | "blend_hot" | "heat" | "whisk_cold" | "whisk_hot" | "reduce" | "saute_simmer" | "crumble" | "custom";
        /** CookingMethodSpecSchema */
        CookingMethodSpecSchema: {
            method: components["schemas"]["CookingMethod"];
            /** Approx Minutes */
            approx_minutes?: number | null;
            /**
             * Can Cook With Others
             * @default true
             */
            can_cook_with_others: boolean;
            /** Notes */
            notes?: string | null;
        };
        /** FeatureWeightsSchema */
        FeatureWeightsSchema: {
            /**
             * Taste Match
             * @default 0.3
             */
            taste_match: number;
            /**
             * Novelty
             * @default 0.2
             */
            novelty: number;
            /**
             * Price Fit
             * @default 0.2
             */
            price_fit: number;
            /**
             * Nutrition Fit
             * @default 0.15
             */
            nutrition_fit: number;
            /**
             * Time Fit
             * @default 0.1
             */
            time_fit: number;
            /**
             * Pantry Bonus
             * @default 0.05
             */
            pantry_bonus: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MacrosSchema */
        MacrosSchema: {
            /** Kcal */
            kcal: number;
            /** Carbs G */
            carbs_g: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Fiber G */
            fiber_g: number;
        };
        /** PortionSchema */
        PortionSchema: {
            /** Value */
            value: number;
            unit: components["schemas"]["PortionUnit"];
        };
        /**
         * PortionUnit
         * @enum {string}
         */
        PortionUnit: "g" | "ml" | "pc";
        /** RecipeBlockSchema */
        RecipeBlockSchema: {
            category: components["schemas"]["Category"];
            /** Title */
            title: string;
            method: components["schemas"]["CookingMethod"];
            /** Components */
            components: components["schemas"]["ComponentRead"][];
            /** Total Minutes */
            total_minutes: number;
            /** Can Cook With Others */
            can_cook_with_others: boolean;
            /** Steps */
            steps: components["schemas"]["RecipeStepSchema"][];
        };
        /** RecipeSchema */
        RecipeSchema: {
            /** Blocks */
            blocks: components["schemas"]["RecipeBlockSchema"][];
            /** Total Minutes */
            total_minutes: number;
        };
        /** RecipeStepSchema */
        RecipeStepSchema: {
            /** Text */
            text: string;
            /**
             * Offset Min
             * @default 0
             */
            offset_min: number;
            /** Duration Min */
            duration_min?: number | null;
        };
        /**
         * RerollSlotRequestSchema
         * @description Re-roll a single slot. The client keeps the rest of the bowl
         *     locally and splices in the returned slot. Server stays stateless.
         */
        RerollSlotRequestSchema: {
            request: components["schemas"]["RollRequestSchema"];
            slot_category: components["schemas"]["Category"];
            /** Exclude Component Ids */
            exclude_component_ids?: string[];
        };
        /** RollRequestSchema */
        RollRequestSchema: {
            /** Slots */
            slots: components["schemas"]["SlotSpecSchema"][];
            /** Dietary Mode */
            dietary_mode?: string | null;
            /** Allergens Excluded */
            allergens_excluded?: string[];
            /** Blacklisted Ids */
            blacklisted_ids?: string[];
            /** Time Budget Min */
            time_budget_min?: number | null;
            /** Forced Methods */
            forced_methods?: {
                [key: string]: components["schemas"]["CookingMethod"];
            };
            /** Recent Component Ids */
            recent_component_ids?: string[];
            weights?: components["schemas"]["FeatureWeightsSchema"];
            /**
             * Temperature
             * @default 0.5
             */
            temperature: number;
            /** Seed */
            seed?: number | null;
        };
        /** RolledBowlSchema */
        RolledBowlSchema: {
            /** Slots */
            slots: components["schemas"]["RolledSlotSchema"][];
        };
        /** RolledSlotSchema */
        RolledSlotSchema: {
            component: components["schemas"]["ComponentRead"];
            /** Score */
            score: number;
            /** Reasons */
            reasons: string[];
        };
        /** SlotSpecSchema */
        SlotSpecSchema: {
            category: components["schemas"]["Category"];
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_components_v1_components_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["Category"] | null;
                include_blacklisted?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_component_v1_components_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_component_v1_components__component_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_component_v1_components__component_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_component_v1_components__component_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roll_bowl_v1_roll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolledBowlSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reroll_one_slot_v1_roll_slot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerollSlotRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolledSlotSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_recipe_endpoint_v1_recipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildRecipeRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
